const ALERT = 'ALERT';
const REFEATCH_CHATS = 'REFEATCH_CHATS';
const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';

export { ALERT, REFEATCH_CHATS, NEW_MESSAGE, NEW_ATTACHMENT };
