const ALERT = 'ALERT';
const REFEATCH_CHATS = 'REFEATCH_CHATS';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';


const NEW_REQUEST = "NEW_REQUEST"

const NEW_MESSAGE = "NEW_MESSAGE"

const CHATTU_TOKEN = "chattu-token"


export { ALERT, REFEATCH_CHATS, NEW_MESSAGE_ALERT, NEW_ATTACHMENT,NEW_REQUEST ,NEW_MESSAGE,CHATTU_TOKEN};
